### ISSUE TITLE
Grey bar in job view

### ISSUE THREAD

**Issue by NotMyFault** [stonega/jenkins-board#21]
Hey,

if I add a job, it occasionally has a grey bar in the scroll part:

https://user-images.githubusercontent.com/13383509/183257956-b5e8235c-de42-44b4-9f37-e5f7c303c682.mp4

The job I added is available on https://ci.jenkins.io/ -> as https://ci.jenkins.io/job/Core/job/jenkins/

I'm using 0.5.1 on MacOS

**Comment by stonega** [comment]
Might a data parse error. I will have a check tomorrow.

**Comment by stonega** [comment]
@NotMyFault  Hi, thanks for your report.
 I have try to fix the issue, the build result is at https://github.com/stonega/jenkins-board/actions/runs/2811599963 , you can download the macos artifact and check if it is fixed.
I also add a setting option to increase panel height.

**Comment by NotMyFault** [comment]
Thanks a bunch!

Scrolling looks much better without the gray bars:

https://user-images.githubusercontent.com/13383509/183279130-3de293cd-15e0-4984-bb35-7906487ac1f7.mp4

**Comment by stonega** [comment]
I have include the fix in v0.5.2 release, so I will close the issue.
Ps: I am using Jenkins Remote Access API in the app, do you know if more detailed docs exist for the api? Thanks!

**Comment by NotMyFault** [comment]
If you're using the remote access API you may find https://www.jenkins.io/doc/book/using/remote-access-api/ useful.
Additionally, every Jenkins page contains an `/api/` endpoint you can add at the end of an URL to obtain useful methods for the page you are on.
